### ISSUE TITLE
Understand statement

### ISSUE THREAD

**Issue by chimosky** [kshitijdshah99/Pippy_Activity#2]
In week 9 you've said "You can drag and drop this image to wherever you need it" when talking about utilizing docker, what did you mean by that?

This too "Indeed, the model would then be running on the server after it was withdrawn."

**Comment by kshitijdshah99** [comment]
Ok so I meant that using the help of docker image we can easily pull the model, it's weights and all it's dependencies which are bundled up together and can deploy it wherever we want by pulling the image.

By the next point I mean that the model could be made to run on the server by pulling it's docker image. This was in reference to our project.

**Comment by chimosky** [comment]
> Ok so I meant that using the help of docker image we can easily pull the model, it's weights and all it's dependencies which are bundled up together and can deploy it wherever we want by pulling the image.

Alright, the drag and drop statement made it confusing as I was wondering where drag and drop comes in.

> By the next point I mean that the model could be made to run on the server by pulling it's docker image. This was in reference to our project.

The use of "withdrawn" in the statement makes it confusing.
